window.__action_constants__ = {
  LOAD_INITIAL_STATE: "LOAD_INITIAL_STATE",
  CHANGE_TITLE: "CHANGE_TITLE",
  CHANGE_LOCATION: "CHANGE_LOCATION",
  CHANGE_ITEM_CATEGORY: "CHANGE_ITEM_CATEGORY",
  CHANGE_ITEM_CALENDAR: "CHANGE_ITEM_CALENDAR",
  CHANGE_START_TIME: "CHANGE_START_TIME",
  CHANGE_END_TIME: "CHANGE_END_TIME",
  TOGGLE_ALL_DAY_EVENT: "TOGGLE_ALL_DAY_EVENT",
  CHANGE_REPEAT_SETTING: "CHANGE_REPEAT_SETTING",
  CHANGE_REMINDER_SETTING: "CHANGE_REMINDER_SETTING",
  CHANGE_DESCRIPTION: "CHANGE_DESCRIPTION",
};
