window.action_constants = {
  CHANGE_TITLE: "CHANGE_TITLE",
  CHANGE_LAYOUT: "CHANGE_LAYOUT",
  TOGGLE_EVENTS_SHOW: "TOGGLE_EVENTS_SHOW",
  TOGGLE_TASKS_SHOW: "TOGGLE_TASKS_SHOW",
  CHANGE_VIEW: "CHANGE_VIEW",
  CHANGE_FROM_DATE: "CHANGE_FROM_DATE",
  CHANGE_TO_DATE: "CHANGE_TO_DATE",
  TOGGLE_TASKS_WITH_NO_DUE_DATE: "TOGGLE_TASKS_WITH_NO_DUE_DATE",
  TOGGLE_COMPLETED_TASKS: "TOGGLE_COMPLETED_TASKS"
};
