window.__action_constants__ = {
  LOAD_INITIAL_STATE: "LOAD_INITIAL_STATE",
  CHANGE_TITLE: "CHANGE_TITLE",
  CHANGE_LOCATION: "CHANGE_LOCATION",
  CHANGE_ITEM_CATEGORY: "CHANGE_ITEM_CATEGORY",
  CHANGE_ITEM_CALENDAR: "CHANGE_ITEM_CALENDAR"
};
